# modified from https://github.com/zhangzilongc/MMR
# copyright (c) 2023 Z.Zhang et al.
# copyright (c) 2025 S.Liao et al.
# Licensed under the Apache License, Version 2.0 (the "LICENSE-APACHE-2.0-ZHANG2023");


RNG_SEED: 54

# set output root dir
OUTPUT_ROOT_DIR: './logs_and_models'
#OUTPUT_DIR: 'aebad_S224/LiMR/original/54_2025_07_02_16_23'


DATASET:
  name: 'aebad_S'
  resize: 256
  imagesize: 224
  subdatasets: ["AeBAD_S"]
  domain_shift_category: "same"

TRAIN:
  enable: False
  save_model: True
  method: 'LiMR'
  change: 'ONNX'
  dataset_path: './datasets/AeBAD'
  backbone: 'resnet34'

  LiMR:
    DA_low_limit: 0.7
    DA_up_limit: 1.
    layers_to_extract_from : ["layer1", "layer2", "layer3"]
    feature_compression : False
    scale_factors : (4.0, 2.0, 1.0)
    FPN_output_dim : (64,128,256,512)
    load_pretrain_model : True
    model_chkpt : "./mobilevitv2_175_layer4.pth"
    finetune_mask_ratio : 0.4
    test_mask_ratio : 0.
    alpha : 1.75
    decoder : 'fpn'
    block_attn_dropout: 0.0
    block_ffn_dropout: 0.0
    block_dropout: 0.1


TRAIN_SETUPS:
  batch_size: 12
  num_workers: 6
  learning_rate: 0.001
  epochs: 2
  weight_decay: 0.05
  warmup_epochs: 15
  save_interval: 20
  tolerance: 0.001
  patience: 10

TEST:
  # When only test, the option is true
  enable: True
  save_segmentation_images: True
#  model_path: r"H:\lsw\abnormal-detection-of-blades-MMR_0.1022.lsw\MMR\logs_and_models\aebad_S224\mobileViTMAE\ablation-LiMR-175-SMR-g-n2\54_2025_06_12_16_02\mobileViTMAE_ablation-LiMR-175-SMR-g-n2_weights_epoch_140.pth"
  model_path: "./best_student_model_175.pth"
#  model_path: r"H:\lsw\abnormal-detection-of-blades-MMR_0.1022.lsw\MMR\logs_and_models\aebad_S224\mobileViTMAE\ablation-LiMR-SMR-h\54_2025_06_15_20_47\mobileViTMAE_ablation-LiMR-SMR-h_weights_epoch_140.pth"
  method: 'LiMR'
  dataset_path: './datasets/AeBAD'
  pixel_mode_verify: True
  TensorRT:
    enable: False
    stu_path: './LiMR_student_16.engine'
    tea_path: './LiMR_teacher_16.engine'
  VISUALIZE:
    Random_sample: True

TEST_SETUPS:
  batch_size: 16